### ISSUE TITLE
Questions about MEDLINE abstracts?

### ISSUE THREAD

**Issue by CharlesChen24** [suamin/MIL-RBERT#2]
First,I am appreciate your sharing code. When I preapre dataset for your code, I have a question about MEDLINE.
you provide https://www.nlm.nih.gov/bsd/medline.html in your paper,but I also fail to find 'medline_abs.txt (~24.5GB)'. I will appreciate it if you can give a link that is more specific.
![1](https://user-images.githubusercontent.com/61905043/102973645-13f15400-4538-11eb-8442-2207accf42f3.jpg)
![2](https://user-images.githubusercontent.com/61905043/102973703-32efe600-4538-11eb-9bea-da5286dfde2c.jpg)

**Comment by wangweifeng2018** [comment]
meet the same issue

**Comment by wangweifeng2018** [comment]
Same issue!
Find the right way?

**Comment by CharlesChen24** [comment]
no

**Comment by CharlesChen24** [comment]
> Same issue!
> Find the right way?

no

**Comment by wangweifeng2018** [comment]
OK， thanksfor your reply.

**Comment by suamin** [comment]
Hi,

Sorry for late response. We have recieved multiple requests regarding this issue and due to some unfortunate data loss we are not able to recover the original script. Therefore, upon reading the PubMed [Terms and Conditions](https://www.nlm.nih.gov/databases/download/terms_and_conditions_pubmed.html) regarding the redistribution, we make the `medline_abs.txt` file available. Please find it here:
https://drive.google.com/drive/folders/1nNZ_DJf8ZLRkb1IOyXxo0PBamjMSvEnK?usp=sharing

Again sorry for this inconvenience. If we recover the abstract extraction script, we will add it to the repository.
